// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_sOG8lh79bXlo4OXq6J7OfldycVLpEi0',
    appId: '1:328445232843:web:111e24f4564e70d847fd4e',
    messagingSenderId: '328445232843',
    projectId: 'maanueat',
    authDomain: 'maanueat.firebaseapp.com',
    storageBucket: 'maanueat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNacqRmB0Ir598URHhhBkDvTEtbBGJvg',
    appId: '1:328445232843:android:6fea65aeca0391ba47fd4e',
    messagingSenderId: '328445232843',
    projectId: 'maanueat',
    storageBucket: 'maanueat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtL2LkKhuG6UJj8EfNHWg-rrukE_SA_4U',
    appId: '1:328445232843:ios:b4b5af4091df9feb47fd4e',
    messagingSenderId: '328445232843',
    projectId: 'maanueat',
    storageBucket: 'maanueat.appspot.com',
    iosBundleId: 'com.example.maanueats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtL2LkKhuG6UJj8EfNHWg-rrukE_SA_4U',
    appId: '1:328445232843:ios:c91e97b11db590f147fd4e',
    messagingSenderId: '328445232843',
    projectId: 'maanueat',
    storageBucket: 'maanueat.appspot.com',
    iosBundleId: 'com.example.maanueats.RunnerTests',
  );
}
